base: /New_Curriculum_Template/
description: A Demo of the League Curriculum websites
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
- - link
  - href: https://www.jointheleague.org/wp-content/uploads/2022/06/favicon-32x32-1.png
    rel: shortcut icon
    type: image/x-icon
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  docsDir: ''
  editLinkText: ''
  editLinks: false
  lastUpdated: false
  logo: /assets/Flag.png
  nav:
  - link: /about/
    text: About
  - link: https://jointheleague.org
    text: The LEAGUE
  repo: ''
  sidebar:
  - path: /
    title: Introduction
  - children:
    - path: /lessons/lesson1/assignment_a/
      title: Assignment A
    collapsable: false
    title: Getting Started
  - children:
    - path: /lessons/lesson2/assignment_b/
      title: Assignment B
    collapsable: false
    path: /lessons/lesson2/
    title: Lesson 2
title: League Demo
